# Generated by Django 5.2.7 on 2025-11-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
    ]
